import type { SetupStatusResponse } from './setupStatusApi';
export type CostPosture = 'free' | 'free-tier' | 'paid' | 'user-owned';
export type SetupStepId = 'choose-path' | 'firebase-client' | 'firebase-admin' | 'gemini' | 'deepseek' | 'massive' | 'alpha-vantage' | 'logo-dev' | 'upstox' | 'splitwise' | 'cas-parser' | 'verify-setup';
export type SetupCategory = 'getting-started' | 'firebase' | 'price-providers' | 'ai-providers' | 'import-providers' | 'connected-accounts' | 'logos' | 'verify';
export interface SetupStepConfig { id: SetupStepId; category: SetupCategory; title: string; description: string; whatItEnables: string; required: boolean; estimatedMinutes: number; costPosture: CostPosture; envKeys: string[]; docsLinks: { label: string; url: string }[]; appRoute?: { label: string; navigateTo: 'settings' | 'docs'; section?: string }; verificationKey: keyof SetupStatusResponse['features'] | null; setupInstructionSteps: string[]; }
export const CATEGORY_ORDER: SetupCategory[] = ['getting-started', 'firebase', 'price-providers', 'ai-providers', 'import-providers', 'logos', 'connected-accounts', 'verify'];
export const CATEGORY_LABELS: Record<SetupCategory, string> = { 'getting-started': 'Choose Setup Path', 'firebase': 'Firebase', 'price-providers': 'Price Providers', 'ai-providers': 'AI Providers', 'import-providers': 'Import Providers', 'logos': 'Logo Provider', 'connected-accounts': 'Connected Accounts', 'verify': 'Verify Setup' };
const s = (id: SetupStepId, cat: SetupCategory, title: string, desc: string, enables: string, req: boolean, min: number, cost: CostPosture, keys: string[], docs: { label: string; url: string }[], route: { label: string; navigateTo: 'settings' | 'docs'; section?: string } | undefined, vk: keyof SetupStatusResponse['features'] | null, steps: string[]): SetupStepConfig => ({ id, category: cat, title, description: desc, whatItEnables: enables, required: req, estimatedMinutes: min, costPosture: cost, envKeys: keys, docsLinks: docs, appRoute: route, verificationKey: vk, setupInstructionSteps: steps });
export const SETUP_STEPS: SetupStepConfig[] = [
  s('choose-path','getting-started','Choose Your Setup Path','Decide how to run Nexus: hosted, BYOK, or self-hosted.','Self-hosted gives full control. Hosted gets you started instantly.',true,2,'free',[],[{label:'Hosted vs Self-Hosted Guide',url:'/docs/setup-modes'}],{label:'Read Docs',navigateTo:'docs'},null,['Hosted: sign in with Google, start tracking.','BYOK: use hosted app with your own keys.','Self-Hosted: clone repo, set up Firebase, deploy.']),
  s('firebase-client','firebase','Firebase Client Config','Configure Firebase web SDK for auth and storage.','User sign-in, shared portfolio, cloud sync, multi-device.',true,5,'free',['NEXT_PUBLIC_FIREBASE_API_KEY','NEXT_PUBLIC_FIREBASE_AUTH_DOMAIN','NEXT_PUBLIC_FIREBASE_PROJECT_ID','NEXT_PUBLIC_FIREBASE_STORAGE_BUCKET','NEXT_PUBLIC_FIREBASE_MESSAGING_SENDER_ID','NEXT_PUBLIC_FIREBASE_APP_ID'],[{label:'Firebase Console',url:'https://console.firebase.google.com'},{label:'Firebase Setup Docs',url:'/docs/setup-modes'}],{label:'Firebase Setup Docs',navigateTo:'docs'},'firebaseAuth',['Create Firebase project (free).','Enable Google sign-in.','Copy config to env vars.']),
  s('firebase-admin','firebase','Firebase Admin SDK','Configure Admin SDK for server-side operations.','Token verification, connected accounts, AI.',true,5,'free',['FIREBASE_ADMIN_PROJECT_ID','FIREBASE_ADMIN_CLIENT_EMAIL','FIREBASE_ADMIN_PRIVATE_KEY'],[{label:'Firebase Service Accounts',url:'https://console.firebase.google.com/project/_/settings/serviceaccounts/adminsdk'},{label:'Admin SDK Docs',url:'/docs/setup-modes'}],{label:'Firebase Setup Docs',navigateTo:'docs'},'firebaseAdmin',['Go to Project Settings > Service Accounts.','Generate private key JSON.','Copy project_id, client_email, private_key.']),
  s('gemini','ai-providers','Google Gemini AI','Set up Gemini for portfolio Q&A and OCR.','AI assistant, Q&A, screenshot import.',false,5,'free-tier',['GEMINI_API_KEY','GOOGLE_API_KEY'],[{label:'Google AI Studio',url:'https://aistudio.google.com/apikey'},{label:'API Keys Docs',url:'/docs/setup-modes'}],{label:'Open AI Settings',navigateTo:'settings',section:'price-providers'},'aiAssistant',['Get API key from Google AI Studio.','Set GEMINI_API_KEY server env var.','Or add key in Settings > AI Provider.']),
  s('deepseek','ai-providers','DeepSeek AI','Configure DeepSeek as alternative AI provider.','Portfolio Q&A via DeepSeek models.',false,5,'paid',[],[{label:'DeepSeek Platform',url:'https://platform.deepseek.com/api_keys'},{label:'API Keys Docs',url:'/docs/setup-modes'}],{label:'Open AI Settings',navigateTo:'settings',section:'price-providers'},null,['Get API key from DeepSeek Platform.','Go to Settings > AI Provider.','Select DeepSeek, paste key, save.']),
  s('massive','price-providers','Massive (US Equity Pricing)','Configure Massive for better US equity coverage.','Better US stock/ETF prices than Yahoo fallback.',false,5,'free-tier',['MASSIVE_API_KEY'],[{label:'Massive API',url:'https://massive.com'},{label:'Pricing Docs',url:'/docs/capability-cost-posture'}],{label:'Price Provider Settings',navigateTo:'settings',section:'price-providers'},'priceRefresh',['Sign up at Massive (free tier).','Set MASSIVE_API_KEY server env.','Restart or redeploy.']),
  s('alpha-vantage','price-providers','Alpha Vantage','Configure Alpha Vantage as alternative price provider.','Additional US/Canada equity pricing.',false,5,'free-tier',['ALPHA_VANTAGE_API_KEY'],[{label:'Alpha Vantage',url:'https://www.alphavantage.co/support/#api-key'},{label:'Pricing Docs',url:'/docs/capability-cost-posture'}],{label:'Price Provider Settings',navigateTo:'settings',section:'price-providers'},'priceRefresh',['Get free API key from Alpha Vantage.','Set ALPHA_VANTAGE_API_KEY server env.','Free tier: 25 requests/day.']),
  s('logo-dev','logos','Logo.dev (Asset Logos)','Enable asset logos in the ledger.','Brand logos alongside holdings.',false,5,'free-tier',['VITE_LOGO_DEV_PUBLISHABLE_KEY','LOGO_DEV_SECRET_KEY'],[{label:'Logo.dev',url:'https://logo.dev'},{label:'Pricing Docs',url:'/docs/capability-cost-posture'}],{label:'Pricing Settings',navigateTo:'settings',section:'price-providers'},'logoProvider',['Sign up at Logo.dev (free tier).','Set VITE_LOGO_DEV_PUBLISHABLE_KEY client-side.','Optionally set LOGO_DEV_SECRET_KEY server-side.']),
  s('upstox','connected-accounts','Upstox (Broker Sync)','Connect Upstox for India portfolio sync.','Cloud holdings, India stock pricing.',false,10,'user-owned',['UPSTOX_CLIENT_ID','UPSTOX_CLIENT_SECRET','UPSTOX_REDIRECT_URI','CONNECTED_ACCOUNTS_ENCRYPTION_KEY','CONNECTED_ACCOUNTS_STATE_SECRET'],[{label:'Upstox Developer Console',url:'https://upstox.com/developer/'},{label:'Integration Docs',url:'/docs/capability-cost-posture'}],{label:'Connected Accounts',navigateTo:'settings',section:'integrations'},'upstoxConnectedAccounts',['Create Upstox developer app.','Set redirect URI and env vars.','Connect in Settings > Integrations.']),
  s('splitwise','connected-accounts','Splitwise (Expenses)','Connect Splitwise for shared expenses.','Expense tracking, group balances.',false,10,'user-owned',['SPLITWISE_CLIENT_ID','SPLITWISE_CLIENT_SECRET','SPLITWISE_REDIRECT_URI','SPLITWISE_STATE_SECRET','INTEGRATION_TOKEN_ENCRYPTION_KEY'],[{label:'Splitwise Developer',url:'https://secure.splitwise.com/apps'},{label:'Integration Docs',url:'/docs/capability-cost-posture'}],{label:'Splitwise Settings',navigateTo:'settings',section:'integrations'},'splitwise',['Register Splitwise app.','Set redirect URI and env vars.','Connect in Settings > Integrations.']),
  s('cas-parser','import-providers','CAS Parser (India MF Import)','Parse CAS PDFs for India mutual fund bulk import.','Bulk import from CAMS/KFintech CAS.',false,5,'free-tier',['CAS_PARSER_SERVICE_URL','CAS_PARSER_API_KEY','CAS_PARSER_ALLOW_EXTERNAL_FALLBACK'],[{label:'CAS Parser Setup',url:'/docs/capability-cost-posture'}],{label:'Import Holdings',navigateTo:'settings',section:'data-management'},'casParser',['Self-host parser (Docker) or use casparser.in cloud.','Set CAS_PARSER_SERVICE_URL or API key.','Go to Settings > Data > Import.']),
  s('verify-setup','verify','Verify Your Setup','Final check that all components work.','Confirms Firebase, Admin, providers, integrations.',true,2,'free',[],[{label:'Troubleshooting Docs',url:'/docs/troubleshooting'}],{label:'Setup Health',navigateTo:'settings',section:'integrations'},null,['Click Check Status for diagnostic.','Green = configured. Missing shows needs.']),
];
export function getStepConfig(id: SetupStepId): SetupStepConfig { const c = SETUP_STEPS.find((x) => x.id === id); if (!c) throw new Error(`Unknown step: ${id}`); return c; }
export type WizardStepState = 'pending' | 'skipped' | 'done';
export interface WizardState { stepStates: Record<SetupStepId, WizardStepState>; currentStepIndex: number; }
export const WIZARD_STORAGE_KEY = 'nexus-wizard-state';
export function loadWizardState(): WizardState | null { try { const r = window.localStorage.getItem(WIZARD_STORAGE_KEY); if (!r) return null; const p = JSON.parse(r); return (p && typeof p.stepStates === 'object' && typeof p.currentStepIndex === 'number') ? p as WizardState : null; } catch { return null; } }
export function saveWizardState(state: WizardState) { try { window.localStorage.setItem(WIZARD_STORAGE_KEY, JSON.stringify(state)); } catch {} }
export function getStepVerificationStatus(step: SetupStepConfig, status: SetupStatusResponse | null): 'configured' | 'missing' | 'unknown' { if (!status || !step.verificationKey) return 'unknown'; const f = status.features[step.verificationKey]; return typeof f === 'boolean' ? (f ? 'configured' : 'missing') : 'unknown'; }
